### ISSUE TITLE
java error when ac_grouping_field is true

### ISSUE THREAD

**Issue by nicolasfranck** [sematext/solr-autocomplete#4]
I've followed the installation guide on this website:
```
https://sematext.com/blog/sematext-solr-autocomplete-introduction-and-howto/
```
and indexed phrases-sponsored.txt into a Solr 6.6.1

When I add the parameter ac_grouping_field=is_sponsored, I get
the error:
```
java.lang.RuntimeException: ReSearcher error at com.sematext.autocomplete.solr.AutoCompleteSearchComponent.doProcess(AutoCompleteSearchComponent.java:204) at com.sematext.solr.handler.component.AbstractReSearcherComponent.process(AbstractReSearcherComponent.java:130) at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:296) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173) at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477) at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723) at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:361) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:305) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) at org.eclipse.jetty.server.Server.handle(Server.java:534) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) at java.lang.Thread.run(Thread.java:745) Caused by: org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Neither qf, df, nor the default search field are present. at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:219) at org.apache.solr.handler.component.ReSearcherHandler.handleSuggestionRequest(ReSearcherHandler.java:167) at org.apache.solr.handler.component.ReSearcherHandler.handleSuggestionResponseRequest(ReSearcherHandler.java:103) at com.sematext.autocomplete.solr.AutoCompleteSearchComponent.doProcess(AutoCompleteSearchComponent.java:306) at com.sematext.autocomplete.solr.AutoCompleteSearchComponent.doProcess(AutoCompleteSearchComponent.java:200) ... 35 more Caused by: org.apache.solr.search.SyntaxError: **Neither qf, df, nor the default search field are present**. at org.apache.solr.search.DisMaxQParser.parseQueryFields(DisMaxQParser.java:77) at org.apache.solr.search.DisMaxQParser.parse(DisMaxQParser.java:104) at org.apache.solr.search.QParser.getQuery(QParser.java:168) at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161) ... 39 more 
```
It complains that neither parameters qf or df are set. It fails in lucene-solr:
https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/search/DisMaxQParser.java#L75

Did I miss something?

**Comment by nicolasfranck** [comment]
After some investigation I discovered that the parameter qf should be "prefixTok matchFullWords^10" (in my case), which wasn't set by the handler automatically

**Comment by otisg** [comment]
Sounds like we can resolve this.
